"""add_stock_impact_to_notes

Revision ID: 0b7c0f8d5ed3
Revises: 9a15f141aa2d
Create Date: 2026-05-08 19:55:10.718060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7c0f8d5ed3'
down_revision: Union[str, None] = '9a15f141aa2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas_credito_debito', sa.Column('afecta_stock', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('notas_credito_debito', sa.Column('stock_tipo', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas_credito_debito', 'stock_tipo')
    op.drop_column('notas_credito_debito', 'afecta_stock')
    # ### end Alembic commands ###
