"""uniques

Revision ID: 9a15f141aa2d
Revises: 
Create Date: 2026-05-08 18:37:34.895568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a15f141aa2d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_laboratorios_nombre', table_name='laboratorios')
    op.create_index(op.f('ix_laboratorios_nombre'), 'laboratorios', ['nombre'], unique=True)
    op.create_index(op.f('ix_proveedores_nombre'), 'proveedores', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proveedores_nombre'), table_name='proveedores')
    op.drop_index(op.f('ix_laboratorios_nombre'), table_name='laboratorios')
    op.create_index('ix_laboratorios_nombre', 'laboratorios', ['nombre'], unique=False)
    # ### end Alembic commands ###
